spring:
  datasource:
    url: jdbc:mysql://localhost/EMP?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect